# llm.py

from prompts import build_system_prompt
from openai import OpenAI
import config

from tools.panel_tools import (
    analyze_panel,
    ANALYZE_PANEL_TOOL,
    composition_analysis,
    COMPOSITION_TOOL,
    generate_reference,
    GENERATE_REFERENCE_TOOL
)

import json
from utils.image_utils import encode_image


openrouter = OpenAI(
    api_key=config.OPENROUTER_API_KEY,
    base_url=config.OPENROUTER_URL
)


# ============================================================
# TOOL MAP
# ============================================================

TOOL_MAP = {
    "analyze_panel": analyze_panel,
    "composition_analysis": composition_analysis,
    "generate_reference": generate_reference,
}


tools = [
    ANALYZE_PANEL_TOOL,
    COMPOSITION_TOOL,
    GENERATE_REFERENCE_TOOL
]


# ============================================================
# HANDLE SINGLE TOOL CALL
# ============================================================

def handle_tool_call(tool_call, panel_image, selected_image):

    print("🔥 HANDLE TOOL CALL EXECUTED")
    print("TOOL NAME:", tool_call.function.name)
    print("PANEL IMAGE:", panel_image)
    print("SELECTED IMAGE:", selected_image)

    fn_name = tool_call.function.name

    # --------------------------------------------------------
    # Check whether tool exists
    # --------------------------------------------------------

    if fn_name not in TOOL_MAP:
        return {
            "role": "tool",
            "content": f"Error: Tool {fn_name} is not supported",
            "tool_call_id": tool_call.id
        }

    # --------------------------------------------------------
    # Analyze Panel / Composition
    # → use panel_image
    # --------------------------------------------------------

    if fn_name in [
        "analyze_panel",
        "composition_analysis"
    ]:

        if not panel_image:
            return {
                "role": "tool",
                "content": "No current panel is available.",
                "tool_call_id": tool_call.id
            }

    # --------------------------------------------------------
    # Generate Reference
    # → use selected_image
    # --------------------------------------------------------

    elif fn_name == "generate_reference":

        if not selected_image:
            return {
                "role": "tool",
                "content": (
                    "No panel has been selected with "
                    "📎 Use Panel."
                ),
                "tool_call_id": tool_call.id
            }

    # --------------------------------------------------------
    # Get arguments generated by the LLM
    # --------------------------------------------------------

    args = json.loads(
        tool_call.function.arguments
    )

    # --------------------------------------------------------
    # Inject application-controlled image path
    # --------------------------------------------------------

    if fn_name in [
        "analyze_panel",
        "composition_analysis"
    ]:

        # The LLM does NOT provide the image path.
        # The application provides panel_image.
        args = {
            "image_path": panel_image
        }

    elif fn_name == "generate_reference":

        # The LLM provides the generation prompt.
        # The application provides selected_image.
        args["image_path"] = selected_image

    # --------------------------------------------------------
    # Execute tool
    # --------------------------------------------------------

    result = TOOL_MAP[fn_name](**args)

    print("🔥 TOOL RESULT:", result)

    return {
        "role": "tool",
        "content": str(result),
        "tool_call_id": tool_call.id
    }


# ============================================================
# HANDLE ALL TOOL CALLS
# ============================================================

def handle_tool_calls(
    message,
    panel_image,
    selected_image
):

    print("🔥 ENTERING handle_tool_calls")

    results = []

    for call in (message.tool_calls or []):

        print(
            "🔥 ABOUT TO EXECUTE:",
            call.function.name
        )

        result = handle_tool_call(
            call,
            panel_image,
            selected_image
        )

        print(
            "🔥 TOOL FINISHED:",
            call.function.name
        )

        results.append(result)

    print("🔥 LEAVING handle_tool_calls")

    return results


# ============================================================
# CLEAN CHAT HISTORY
# ============================================================

def clean_history(history):

    cleaned = []

    for h in history:

        content = h["content"]

        if isinstance(content, list):

            text_parts = []

            for item in content:

                if isinstance(item, str):
                    text_parts.append(item)

            content = " ".join(text_parts)

        cleaned.append({
            "role": h["role"],
            "content": content
        })

    return cleaned


# ============================================================
# CONVERT ASSISTANT TOOL CALL MESSAGE
# ============================================================

def assistant_tool_message(assistant_message):

    return {
        "role": "assistant",
        "content": assistant_message.content,

        "tool_calls": [
            {
                "id": call.id,
                "type": "function",
                "function": {
                    "name": call.function.name,
                    "arguments": call.function.arguments
                }
            }

            for call in (assistant_message.tool_calls or [])
        ]
    }


print("🚨 NEW LLM.PY VERSION RUNNING")


# ============================================================
# MAIN CHAT FUNCTION
# ============================================================

def craft_response(
    message,
    history,
    panel_image,
    selected_image
):

    # --------------------------------------------------------
    # Chatbot requires an explicitly selected panel
    # --------------------------------------------------------

    if not selected_image:

        return (
            "Please click **📎 Use Panel** "
            "to select a panel before asking me to analyze it."
        )

    # --------------------------------------------------------
    # Clean previous conversation
    # --------------------------------------------------------

    history = clean_history(history)

    relevant_system_prompt = build_system_prompt(message)

    # --------------------------------------------------------
    # User message
    # --------------------------------------------------------

    user_content = [
        {
            "type": "text",
            "text": message
        }
    ]

    # --------------------------------------------------------
    # Send selected panel to the first LLM
    # --------------------------------------------------------

    # image_data = encode_image(selected_image)

    # user_content.append(
    #     {
    #         "type": "image_url",
    #         "image_url": {
    #             "url": image_data
    #         }
    #     }
    # )

    messages = (
        [
            {
                "role": "system",
                "content": relevant_system_prompt
            }
        ]
        + history
        + [
            {
                "role": "user",
                "content": user_content
            }
        ]
    )

    # ========================================================
    # FIRST LLM CALL
    # ========================================================

    response = openrouter.chat.completions.create(
        model=config.MODEL,
        messages=messages,
        max_completion_tokens=2000,
        tools=tools
    )

    print(
        "\n========== FIRST LLM RESPONSE =========="
    )

    print(
        "FINISH REASON:",
        response.choices[0].finish_reason
    )

    print(
        "TOOL CALLS:",
        response.choices[0].message.tool_calls
    )

    print(
        "MESSAGE:",
        response.choices[0].message
    )

    print(
        "========================================\n"
    )

    # ========================================================
    # TOOL-CALL LOOP
    # ========================================================

    while (
        response.choices[0].finish_reason
        == "tool_calls"
    ):

        assistant_message = response.choices[0].message

        # ----------------------------------------------------
        # Add assistant tool-call message
        # ----------------------------------------------------

        messages.append(
            assistant_tool_message(
                assistant_message
            )
        )

        # ----------------------------------------------------
        # Execute ALL requested tools
        # ----------------------------------------------------

        tool_results = handle_tool_calls(
            assistant_message,
            panel_image,
            selected_image
        )

        # ----------------------------------------------------
        # Add tool results
        # ----------------------------------------------------

        messages.extend(tool_results)

        print(
            "🔥🔥 REACHED AFTER TOOL RESULTS"
        )

        # ====================================================
        # DEBUG TOOL RESULTS
        # ====================================================

        print(
            "\n========== TOOLS EXECUTED =========="
        )

        for result in tool_results:

            print(
                "TOOL RESULT:",
                result["tool_call_id"],
                "LENGTH:",
                len(result["content"])
            )

        print(
            "=====================================\n"
        )

        # ====================================================
        # TOOL RESULTS → CONVERSATION-AWARE LLM
        # ====================================================

        messages.append(
            {
                "role": "user",
                "content": """
Answer the user's original request using the tool results above.

You are the conversational reasoning layer.

Important rules:

- Answer the user's specific question, not a generic panel analysis.
- Use the tool results as the primary source of visual information.
- Use relevant conversation history when it helps resolve references such as
  "this panel", "that pose", "the lighting", or "the previous analysis".
- Do not repeat unrelated information from the tool results.
- Do not invent visual details that are not supported by the tool results.
- If the user asks about one specific concept, focus on that concept.
- If the user asks for a broad analysis, combine the relevant tool results.
- Give a natural conversational answer.
"""
            }
        )

        print(
            "\n🔥 TOOL RESULTS → "
            "CONVERSATION-AWARE LLM\n"
        )

        print("\n========== MESSAGES SENT TO SYNTHESIS LLM ==========")

        for i, msg in enumerate(messages):

            print(f"\n--- MESSAGE {i} ---")
            print("ROLE:", msg.get("role"))

            content = msg.get("content")

            if isinstance(content, list):

                for item in content:

                    if item.get("type") == "text":
                        print(
                            "TEXT:",
                            item.get("text")
                        )

                    elif item.get("type") == "image_url":
                        print(
                            "IMAGE: <base64 image data omitted>"
                        )

            else:
                print(
                    "CONTENT:",
                    content
                )

        print("\n====================================================\n")   

        # ----------------------------------------------------
        # SYNTHESIS LLM CALL
        # ----------------------------------------------------

        response = openrouter.chat.completions.create(
            model=config.MODEL,
            messages=messages,
            max_completion_tokens=2000
        )

        print(
            "\n========== SYNTHESIS LLM RESPONSE =========="
        )

        print(
            "FINISH REASON:",
            response.choices[0].finish_reason
        )

        print(
            "TOOL CALLS:",
            response.choices[0].message.tool_calls
        )

        print(
            "CONTENT:",
            response.choices[0].message.content
        )

        print(
            "========================================\n"
        )

    # ========================================================
    # FINAL RESPONSE
    # ========================================================

    final_message = response.choices[0].message

    if final_message.content is None:

        return (
            "I couldn't generate a final response "
            "after analyzing the panel."
        )

    return final_message.content



