# llm.py

from prompts import build_system_prompt
from openai import OpenAI
import config

from tools.panel_tools import (
    analyze_panel,
    ANALYZE_PANEL_TOOL,
    composition_analysis,
    COMPOSITION_TOOL,
    generate_reference,
    GENERATE_REFERENCE_TOOL
)

import json
from utils.image_utils import encode_image


openrouter = OpenAI(
    api_key=config.OPENROUTER_API_KEY,
    base_url=config.OPENROUTER_URL
)


# ============================================================
# TOOL MAP
# ============================================================

TOOL_MAP = {
    "analyze_panel": analyze_panel,
    "composition_analysis": composition_analysis,
    "generate_reference": generate_reference,
}


ALL_TOOLS = [
    ANALYZE_PANEL_TOOL,
    COMPOSITION_TOOL,
    GENERATE_REFERENCE_TOOL
]


# ============================================================
# DETERMINE USER INTENT
# ============================================================

def requires_visual_context(message):

    text = message.lower().strip()

    visual_phrases = [
        "this panel",
        "that panel",
        "the panel",
        "this image",
        "that image",
        "the image",
        "what is happening",
        "what do you see",
        "analyze",
        "analyse",
        "describe this",
        "composition",
        "camera angle",
        "shot type",
        "perspective",
        "pose",
        "body language",
        "facial expression",
        "lighting",
        "shading",
        "shadow",
        "background",
        "character position",
        "character positioning",
        "visual depth",
        "spatial relationship"
    ]

    return any(
        phrase in text
        for phrase in visual_phrases
    )


def requires_reference_generation(message):

    text = message.lower().strip()

    generation_phrases = [
        "generate reference",
        "generate a reference",
        "create reference",
        "create a reference",
        "make a reference",
        "generate image",
        "generate an image",
        "create image",
        "create an image",
        "make an image",
        "reference image"
    ]

    return any(
        phrase in text
        for phrase in generation_phrases
    )


# ============================================================
# SELECT TOOLS FOR CURRENT REQUEST
# ============================================================

def get_tools_for_request(message):

    if requires_reference_generation(message):

        print("🎨 REQUEST TYPE: REFERENCE GENERATION")

        return [
            GENERATE_REFERENCE_TOOL
        ]

    if requires_visual_context(message):

        print("👁️ REQUEST TYPE: VISUAL ANALYSIS")

        return [
            ANALYZE_PANEL_TOOL,
            COMPOSITION_TOOL
        ]

    print("💬 REQUEST TYPE: NORMAL CONVERSATION")

    return []


# ============================================================
# HANDLE SINGLE TOOL CALL
# ============================================================

def handle_tool_call(
    tool_call,
    panel_image,
    selected_image
):

    print("🔥 HANDLE TOOL CALL EXECUTED")
    print("TOOL NAME:", tool_call.function.name)
    print("PANEL IMAGE:", panel_image)
    print("SELECTED IMAGE:", selected_image)

    fn_name = tool_call.function.name

    # --------------------------------------------------------
    # Check whether tool exists
    # --------------------------------------------------------

    if fn_name not in TOOL_MAP:

        return {
            "role": "tool",
            "content": (
                f"Error: Tool {fn_name} "
                "is not supported"
            ),
            "tool_call_id": tool_call.id
        }

    # --------------------------------------------------------
    # Analyze Panel / Composition
    #
    # IMPORTANT:
    # These tools operate on panel_image.
    # --------------------------------------------------------

    if fn_name in [
        "analyze_panel",
        "composition_analysis"
    ]:

        if not panel_image:

            return {
                "role": "tool",
                "content": (
                    "No uploaded panel image "
                    "is available."
                ),
                "tool_call_id": tool_call.id
            }

    # --------------------------------------------------------
    # Generate Reference
    #
    # IMPORTANT:
    # Generate Reference operates on selected_image.
    # --------------------------------------------------------

    elif fn_name == "generate_reference":

        if not selected_image:

            return {
                "role": "tool",
                "content": (
                    "No panel has been selected with "
                    "📎 Use Panel."
                ),
                "tool_call_id": tool_call.id
            }

    # --------------------------------------------------------
    # Get arguments generated by the LLM
    # --------------------------------------------------------

    try:

        args = json.loads(
            tool_call.function.arguments
        )

    except json.JSONDecodeError:

        return {
            "role": "tool",
            "content": (
                "Error: Invalid tool arguments "
                "generated by the model."
            ),
            "tool_call_id": tool_call.id
        }

    # --------------------------------------------------------
    # Inject application-controlled image path
    # --------------------------------------------------------

    if fn_name in [
        "analyze_panel",
        "composition_analysis"
    ]:

        # The LLM does NOT provide the image path.
        #
        # The application controls which uploaded
        # panel is analyzed.

        args = {
            "image_path": panel_image
        }

    elif fn_name == "generate_reference":

        # The LLM provides the generation prompt.
        #
        # The application controls which selected
        # panel is used.

        args["image_path"] = selected_image

    # --------------------------------------------------------
    # Execute tool
    # --------------------------------------------------------

    if fn_name == "generate_reference":

        # Do NOT generate the image here.
        #
        # The LLM only prepares the request.
        # Actual generation happens when the user
        # clicks the Generate Reference button.

        result = (
            "Generation request captured successfully. "
            "The reference image will be generated when "
            "the user clicks the Generate Reference button."
        )

    else:

        result = TOOL_MAP[fn_name](**args)

    print("🔥 TOOL RESULT:", result)

    return {
        "role": "tool",
        "content": str(result),
        "tool_call_id": tool_call.id
    }


# ============================================================
# HANDLE ALL TOOL CALLS
# ============================================================

def handle_tool_calls(
    message,
    panel_image,
    selected_image
):

    print("🔥 ENTERING handle_tool_calls")

    results = []

    for call in (message.tool_calls or []):

        print(
            "🔥 ABOUT TO EXECUTE:",
            call.function.name
        )

        result = handle_tool_call(
            call,
            panel_image,
            selected_image
        )

        print(
            "🔥 TOOL FINISHED:",
            call.function.name
        )

        results.append(result)

    print("🔥 LEAVING handle_tool_calls")

    return results


# ============================================================
# CLEAN CHAT HISTORY
# ============================================================

def clean_history(history):

    cleaned = []

    for h in history:

        content = h["content"]

        if isinstance(content, list):

            text_parts = []

            for item in content:

                if isinstance(item, str):
                    text_parts.append(item)

                elif isinstance(item, dict):

                    if item.get("type") == "text":

                        text_parts.append(
                            item.get("text", "")
                        )

            content = " ".join(text_parts)

        cleaned.append({
            "role": h["role"],
            "content": content
        })

    return cleaned


# ============================================================
# CONVERT ASSISTANT TOOL CALL MESSAGE
# ============================================================

def assistant_tool_message(assistant_message):

    return {
        "role": "assistant",
        "content": assistant_message.content,

        "tool_calls": [
            {
                "id": call.id,
                "type": "function",
                "function": {
                    "name": call.function.name,
                    "arguments": call.function.arguments
                }
            }

            for call in (
                assistant_message.tool_calls or []
            )
        ]
    }


print("🚨 NEW LLM.PY VERSION RUNNING")


# ============================================================
# MAIN CHAT FUNCTION
# ============================================================

def craft_response(
    message,
    history,
    panel_image,
    selected_image
):

    generation_request = None

    # ========================================================
    # DETERMINE REQUEST TYPE
    # ========================================================

    needs_visual_context = (
        requires_visual_context(message)
    )

    needs_reference_generation = (
        requires_reference_generation(message)
    )

    print(
        "\n========== REQUEST ROUTING =========="
    )

    print(
        "MESSAGE:",
        message
    )

    print(
        "NEEDS VISUAL CONTEXT:",
        needs_visual_context
    )

    print(
        "NEEDS REFERENCE GENERATION:",
        needs_reference_generation
    )

    # ========================================================
    # VALIDATE REQUIRED PANEL
    # ========================================================

    if needs_visual_context and not selected_image:

        return (
            "Please click **📎 Use Panel** "
            "to select a panel before asking me "
            "to analyze it.",
            None
        )

    if needs_reference_generation and not selected_image:

        return (
            "Please click **📎 Use Panel** "
            "to select a panel before generating "
            "a reference.",
            None
        )

    # ========================================================
    # SELECT TOOLS
    # ========================================================

    request_tools = get_tools_for_request(message)

    print(
        "TOOLS ENABLED:",
        [
            tool["function"]["name"]
            for tool in request_tools
        ]
    )

    print(
        "====================================\n"
    )

    # ========================================================
    # CLEAN PREVIOUS CONVERSATION
    # ========================================================

    history = clean_history(history)

    relevant_system_prompt = (
        build_system_prompt(message)
    )

    # ========================================================
    # CURRENT USER MESSAGE
    # ========================================================

    user_content = [
        {
            "type": "text",
            "text": message
        }
    ]

    # --------------------------------------------------------
    # Attach selected panel only when the current request
    # actually requires visual context.
    # --------------------------------------------------------

    if (
        (needs_visual_context or needs_reference_generation)
        and selected_image
    ):

        image_data = encode_image(
            selected_image
        )

        user_content.append(
            {
                "type": "image_url",
                "image_url": {
                    "url": image_data
                }
            }
        )

        print(
            "🖼️ SELECTED PANEL ATTACHED TO LLM"
        )

    else:
        
        print(
            "📝 NO IMAGE ATTACHED TO LLM"
        )



    # ========================================================
    # BUILD MESSAGES
    # ========================================================

    messages = (
        [
            {
                "role": "system",
                "content": relevant_system_prompt
            }
        ]
        + history
        + [
            {
                "role": "user",
                "content": user_content
            }
        ]
    )

    # ========================================================
    # FIRST LLM CALL
    # ========================================================

    request_kwargs = {
        "model": config.MODEL,
        "messages": messages,
        "max_completion_tokens": 2000
    }

    # --------------------------------------------------------
    # CRITICAL ARCHITECTURE:
    #
    # Do NOT send tools for normal conversation.
    # --------------------------------------------------------

    if request_tools:

        request_kwargs["tools"] = request_tools

    response = openrouter.chat.completions.create(
        **request_kwargs
    )

    # ========================================================
    # DEBUG FIRST RESPONSE
    # ========================================================

    print(
        "\n========== FIRST LLM RESPONSE =========="
    )

    print(
        "FINISH REASON:",
        response.choices[0].finish_reason
    )

    print(
        "TOOL CALLS:",
        response.choices[0].message.tool_calls
    )

    for call in (
        response.choices[0].message.tool_calls or []
    ):

        print("\n🔥 TOOL NAME:")
        print(call.function.name)

        print("🔥 TOOL ARGUMENTS:")
        print(call.function.arguments)

    print(
        "MESSAGE:",
        response.choices[0].message
    )

    print(
        "========================================\n"
    )

    # ========================================================
    # TOOL-CALL LOOP
    # ========================================================

    while (
        response.choices[0].finish_reason
        == "tool_calls"
    ):

        assistant_message = (
            response.choices[0].message
        )

        # ----------------------------------------------------
        # Capture generation request
        # ----------------------------------------------------

        for call in (
            assistant_message.tool_calls or []
        ):

            if (
                call.function.name
                == "generate_reference"
            ):

                try:

                    args = json.loads(
                        call.function.arguments
                    )

                    generation_request = (
                        args.get("prompt")
                    )

                except json.JSONDecodeError:

                    generation_request = None

                print(
                    "\n🎨 GENERATION REQUEST CAPTURED:"
                )

                print(
                    generation_request
                )

                print(
                    "================================\n"
                )

        # ----------------------------------------------------
        # Add assistant tool-call message
        # ----------------------------------------------------

        messages.append(
            assistant_tool_message(
                assistant_message
            )
        )

        # ----------------------------------------------------
        # Execute requested tools
        # ----------------------------------------------------

        tool_results = handle_tool_calls(
            assistant_message,
            panel_image,
            selected_image
        )

        # ----------------------------------------------------
        # Add tool results
        # ----------------------------------------------------

        messages.extend(
            tool_results
        )

        # ====================================================
        # GENERATE REFERENCE
        # ====================================================

        if generation_request:

            print(
                "\n🎨 GENERATION REQUEST READY"
            )

            return (
                "🎨 Generation request captured!\n\n"
                "Click **Generate Reference** in "
                "the Panel Tools to create the image.",
                generation_request
            )

        # ====================================================
        # TOOL RESULTS → LLM
        # ====================================================

        messages.append(
            {
                "role": "user",
                "content": (
                    "Answer the user's original "
                    "request using the tool results "
                    "above."
                )
            }
        )

        print(
            "\n🔥 TOOL RESULTS → "
            "CONVERSATION-AWARE LLM\n"
        )

        # ----------------------------------------------------
        # SYNTHESIS CALL
        # ----------------------------------------------------

        response = openrouter.chat.completions.create(
            model=config.MODEL,
            messages=messages,
            max_completion_tokens=2000
        )

        print(
            "\n========== SYNTHESIS LLM RESPONSE =========="
        )

        print(
            "FINISH REASON:",
            response.choices[0].finish_reason
        )

        print(
            "TOOL CALLS:",
            response.choices[0].message.tool_calls
        )

        print(
            "CONTENT:",
            response.choices[0].message.content
        )

        print(
            "========================================\n"
        )

    # ========================================================
    # FINAL RESPONSE
    # ========================================================

    final_message = (
        response.choices[0].message
    )

    if final_message.content is None:

        return (
            "I couldn't generate a final response.",
            generation_request
        )

    return (
        final_message.content,
        generation_request
    )